
import styles from '@/styles/globals.module.css'

export const metadata = {
	title: 'Metal Group',
	description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={styles.body}>{children}</body>
		</html>
	)
}
