const products = [
	{
		id: 1,
		title: 'square_bars',
		image: '/squarebars.jpg',
		sizes: [
			{ value: '8x8', unit: 'meters' },
			{ value: '10x10', unit: 'meters' },
			{ value: '12x12', unit: 'meters' },
			{ value: '14x14', unit: 'meters' },
			{ value: '16x16', unit: 'meters' },
			{ value: '20x20', unit: 'meters' },
		],
		description: {
			en: 'Square bars are used in a variety of applications including construction, manufacturing, and heavy equipment. Their solid structure provides durability and strength for industrial projects.',
			ru: 'Квадратные стержни используются в различных областях, включая строительство, производство и тяжелое оборудование. Их прочная структура обеспечивает долговечность и прочность для промышленных проектов.',
			ka: 'კვადრატული ბარები გამოიყენება სხვადასხვა გამოყენებისთვის, მათ შორის მშენებლობა, წარმოება და მძიმე აღჭურვილობა. მათი მყარი სტრუქტურა უზრუნველყოფს გამძლეობას და სიძლიერეს სამრეწველო პროექტებისთვის.',
		},
		specifications: {
			en: [
				'Material: Carbon Steel',
				'Tensile Strength: 400 MPa',
				'Yield Strength: 250 MPa',
				'Length: Up to 6 meters',
				'Surface Finish: Black, Galvanized',
			],
			ru: [
				'Материал: углеродистая сталь',
				'Предел прочности на разрыв: 400 МПа',
				'Предел текучести: 250 МПа',
				'Длина: до 6 метров',
				'Поверхность: черная, оцинкованная',
			],
			ka: [
				'მასალა: ნახშირბადის ფოლადი',
				'წყვეტვის მდგრადობა: 400 MPa',
				'გამოსატანი მდგრადობა: 250 MPa',
				'სიგრძე: 6 მეტრამდე',
				'ზედაპირი: შავი, გალვანიზირებული',
			],
		},
	},
	{
		id: 2,
		title: 'square_profile',
		image: '/squareprofile.jpg',
		sizes: [
			{ value: '10x10x1', unit: 'meters' },
			{ value: '10x20x1.5', unit: 'meters' },
			{ value: '10x30x1.5', unit: 'meters' },
			{ value: '15x15x1.2', unit: 'meters' },
			{ value: '15x15x1.5', unit: 'meters' },
			{ value: '20x20x1.5', unit: 'meters' },
			{ value: '20x20x2', unit: 'meters' },
			{ value: '20x30x1.5', unit: 'meters' },
			{ value: '20x30x2', unit: 'meters' },
			{ value: '20x40x1.5', unit: 'meters' },
			{ value: '20x40x2', unit: 'meters' },
			{ value: '20x50x1.5', unit: 'meters' },
			{ value: '20x50x2', unit: 'meters' },
			{ value: '20x60x2', unit: 'meters' },
			{ value: '25x25x1.5', unit: 'meters' },
			{ value: '25x25x2', unit: 'meters' },
			{ value: '25x40x2', unit: 'meters' },
			{ value: '25x50x2', unit: 'meters' },
			{ value: '30x30x1.5', unit: 'meters' },
			{ value: '30x30x2', unit: 'meters' },
			{ value: '30x40x2', unit: 'meters' },
			{ value: '30x50x2', unit: 'meters' },
			{ value: '30x60x2', unit: 'meters' },
			{ value: '30x60x3', unit: 'meters' },
			{ value: '40x40x1.5', unit: 'meters' },
			{ value: '40x40x2', unit: 'meters' },
			{ value: '40x40x3', unit: 'meters' },
			{ value: '40x50x2', unit: 'meters' },
			{ value: '40x60x3', unit: 'meters' },
			{ value: '40x80x1.5', unit: 'meters' },
			{ value: '40x80x2', unit: 'meters' },
			{ value: '40x80x3', unit: 'meters' },
			{ value: '40x100x2', unit: 'meters' },
			{ value: '40x100x2.5', unit: 'meters' },
			{ value: '50x50x2', unit: 'meters' },
			{ value: '50x50x3', unit: 'meters' },
			{ value: '50x100x2', unit: 'meters' },
			{ value: '50x100x3', unit: 'meters' },
			{ value: '60x60x2', unit: 'meters' },
			{ value: '60x60x3', unit: 'meters' },
			{ value: '60x80x2', unit: 'meters' },
			{ value: '60x80x3', unit: 'meters' },
			{ value: '60x100x2', unit: 'meters' },
			{ value: '60x100x3', unit: 'meters' },
			{ value: '60x120x2', unit: 'meters' },
			{ value: '60x120x3', unit: 'meters' },
			{ value: '70x70x2', unit: 'meters' },
			{ value: '70x70x3', unit: 'meters' },
			{ value: '80x80x2', unit: 'meters' },
			{ value: '80x80x3', unit: 'meters' },
			{ value: '80x80x4', unit: 'meters' },
			{ value: '80x120x3', unit: 'meters' },
			{ value: '80x120x4', unit: 'meters' },
			{ value: '80x160x3', unit: 'meters' },
			{ value: '80x160x4', unit: 'meters' },
			{ value: '100x100x2', unit: 'meters' },
			{ value: '100x100x2.5', unit: 'meters' },
			{ value: '100x100x3', unit: 'meters' },
			{ value: '100x100x4', unit: 'meters' },
			{ value: '100x100x6', unit: 'meters' },
			{ value: '100x150x3', unit: 'meters' },
			{ value: '100x200x4', unit: 'meters' },
			{ value: '120x120x3', unit: 'meters' },
			{ value: '120x120x4', unit: 'meters' },
			{ value: '120x120x5', unit: 'meters' },
			{ value: '120x120x6', unit: 'meters' },
			{ value: '150x150x3', unit: 'meters' },
			{ value: '150x150x4', unit: 'meters' },
			{ value: '150x150x5', unit: 'meters' },
			{ value: '200x200x5', unit: 'meters' },
		],
		description: {
			en: 'Square profiles are versatile and can be used in a variety of structural and decorative applications. They offer strength and support while being lightweight and easy to handle.',
			ru: 'Квадратные профили универсальны и могут использоваться в различных конструктивных и декоративных приложениях. Они обеспечивают прочность и поддержку, оставаясь легкими и удобными в обращении.',
			ka: 'კვადრატული პროფილები მრავალმხრივია და შეიძლება გამოყენებულ იქნას სხვადასხვა სტრუქტურულ და დეკორატიულ დანიშნულებებში. ისინი უზრუნველყოფენ ძალას და მხარდაჭერას, რჩებიან მსუბუქი და ადვილად დასამუშავებელი.',
		},
		specifications: {
			en: [
				'Material: Stainless Steel',
				'Wall Thickness: 1-5 mm',
				'Length: Up to 12 meters',
				'Surface Finish: Polished, Brushed, Satin',
			],
			ru: [
				'Материал: нержавеющая сталь',
				'Толщина стенки: 1-5 мм',
				'Длина: до 12 метров',
				'Поверхность: полированная, матовая, сатиновая',
			],
			ka: [
				'მასალა: უჟანგავი ფოლადი',
				'კედლის სისქე: 1-5 მმ',
				'სიგრძე: 12 მეტრამდე',
				'ზედაპირი: გაპოლირებული, ნაკაწრი, სასატინო',
			],
		},
	},
	{
		id: 3,
		title: 'steel_pipe',
		image: '/steelpipe.webp',
		sizes: [
			{ value: '21.3*2.5', unit: 'meters' },
			{ value: '26.9*2.5', unit: 'meters' },
			{ value: '33*2.5', unit: 'meters' },
			{ value: '42*2.5', unit: 'meters' },
			{ value: '48*2.5', unit: 'meters' },
			{ value: '48*3', unit: 'meters' },
			{ value: '57*2.5', unit: 'meters' },
			{ value: '57*3', unit: 'meters' },
			{ value: '76*3', unit: 'meters' },
			{ value: '89*3', unit: 'meters' },
			{ value: '89*3.5', unit: 'meters' },
			{ value: '102*3', unit: 'meters' },
			{ value: '102*3.5', unit: 'meters' },
			{ value: '108*4', unit: 'meters' },
			{ value: '114*4', unit: 'meters' },
			{ value: '127*4', unit: 'meters' },
			{ value: '159*4', unit: 'meters' },
			{ value: '159*4.5', unit: 'meters' },
			{ value: '219.1*4', unit: 'meters' },
			{ value: '219.1*4.5', unit: 'meters' },
		],
		description: {
			en: 'Steel pipes are commonly used in construction, plumbing, and manufacturing. They provide a robust and durable solution for transporting fluids and gases.',
			ru: 'Стальные трубы широко используются в строительстве, сантехнике и производстве. Они обеспечивают надежное и долговечное решение для транспортировки жидкостей и газов.',
			ka: 'რკინის მილები ფართოდ გამოიყენება მშენებლობაში, პლომბირებაში და წარმოებაში. ისინი უზრუნველყოფენ მტკიცე და გამძლე გადაწყვეტილებას სითხეების და გაზების ტრანსპორტირებისთვის.',
		},
		specifications: {
			en: [
				'Material: Carbon Steel',
				'Diameter: 21.3-219.1 mm',
				'Wall Thickness: 2.5-4.5 mm',
				'Length: Up to 6 meters',
				'Coating: Anti-corrosion',
			],
			ru: [
				'Материал: углеродистая сталь',
				'Диаметр: 21.3-219.1 мм',
				'Толщина стенки: 2.5-4.5 мм',
				'Длина: до 6 метров',
				'Покрытие: Антикоррозийное',
			],
			ka: [
				'მასალა: ნახშირბადის ფოლადი',
				'დიამეტრი: 21.3-219.1 მმ',
				'კედლის სისქე: 2.5-4.5 მმ',
				'სიგრძე: 6 მეტრამდე',
				'საწინააღმდეგო კოროზიული საფარით',
			],
		},
	},
	{
		id: 4,
		title: 'steel_sheet',
		image: '/steelsheet.jpg',
		sizes: [
			{ value: '0.35x1x2', unit: 'pieces' },
			{ value: '0.40x1x2', unit: 'pieces' },
			{ value: '0.5x1x2', unit: 'pieces' },
			{ value: '0.8x1x2', unit: 'pieces' },
			{ value: '0.8x1.25x2.5', unit: 'pieces' },
			{ value: '1.0x1x2', unit: 'pieces' },
			{ value: '1.0x1.25x2.5', unit: 'pieces' },
			{ value: '1.2x1.25x2.5', unit: 'pieces' },
			{ value: '1.4x1x2', unit: 'pieces' },
			{ value: '1.4x1x25x2.5', unit: 'pieces' },
			{ value: '1.9x1x2', unit: 'pieces' },
			{ value: '2.0x1x2', unit: 'pieces' },
			{ value: '2.0x1x2.2', unit: 'pieces' },
			{ value: '2.0x1x2.3', unit: 'pieces' },
			{ value: '2.0x1x2.5', unit: 'pieces' },
			{ value: '2.0x1.25x2.5', unit: 'pieces' },
			{ value: '2.5x1.25x2.', unit: 'pieces' },
			{ value: '2.8x1.25x2.5', unit: 'pieces' },
			{ value: '3.0x1x2', unit: 'pieces' },
			{ value: '4x1.25x4', unit: 'pieces' },
			{ value: '4x1.5x6', unit: 'pieces' },
			{ value: '5x1.5x6', unit: 'pieces' },
			{ value: '6x1.5x6', unit: 'pieces' },
			{ value: '8x1.5x6', unit: 'pieces' },
			{ value: '10x1.5x6', unit: 'pieces' },
			{ value: '12x1.5x6', unit: 'pieces' },
			{ value: '15x1.5x6', unit: 'pieces' },
			{ value: '20x1.5x6', unit: 'pieces' },
			{ value: '25x1.5x6', unit: 'pieces' },
			{ value: '30x1.5x6', unit: 'pieces' },
			{ value: '40x1.5x6', unit: 'pieces' },
			{ value: '50x1.5x6', unit: 'pieces' },
		],
		description: {
			en: 'Steel sheets are versatile materials used in a variety of industries including automotive, construction, and manufacturing. They are available in different thicknesses and finishes.',
			ru: 'Стальные листы являются универсальными материалами, используемыми в различных отраслях, включая автомобильную, строительную и производственную. Они доступны в различных толщине и отделках.',
			ka: 'რკინის ფურცლები მრავალფეროვანი მასალებია, რომლებიც გამოიყენება სხვადასხვა ინდუსტრიებში, მათ შორის ავტომობილების, მშენებლობის და წარმოების სფეროებში. ისინი ხელმისაწვდომია სხვადასხვა სისქეებითა და დასრულებებით.',
		},
		specifications: {
			en: [
				'Material: Stainless Steel',
				'Thickness: 0.35-2 mm',
				'Dimensions: 1x2 meters',
				'Surface Finish: Polished, Matte, Brushed',
			],
			ru: [
				'Материал: нержавеющая сталь',
				'Толщина: 0.35-2 мм',
				'Размеры: 1x2 метра',
				'Поверхностная отделка: Полированная, Матовая, Шлифованная',
			],
			ka: [
				'მასალა: უჟანგავი ფოლადი',
				'სისქე: 0.35-2 მმ',
				'ზომები: 1x2 მეტრი',
				'ზედაპირის დასრულება: პოლირებული, მატовая, დამუშავებული',
			],
		},
	},
	{
		id: 5,
		title: 'u_profile',
		image: '/uprofile.webp',
		sizes: [
			{ value: '6', unit: 'meters' },
			{ value: '8', unit: 'meters' },
			{ value: '10', unit: 'meters' },
			{ value: '12', unit: 'meters' },
			{ value: '14', unit: 'meters' },
			{ value: '16', unit: 'meters' },
			{ value: '18', unit: 'meters' },
			{ value: '20', unit: 'meters' },
			{ value: '22', unit: 'meters' },
			{ value: '24', unit: 'meters' },
			{ value: '27', unit: 'meters' },
			{ value: '30', unit: 'meters' },
		],
		description: {
			en: 'U profiles, also known as channels, are commonly used in structural applications. Their unique shape provides excellent load-bearing capabilities.',
			ru: 'U-профили, также известные как каналы, часто используются в конструктивных приложениях. Их уникальная форма обеспечивает отличные несущие способности.',
			ka: 'U პროფილები, ასევე ცნობილი როგორც არხები, ფართოდ გამოიყენება სტრუქტურულ აპლიკაციებში. მათი უნიკალური ფორმა უზრუნველყოფს შესანიშნავ დატვირთვის ძალას.',
		},
		specifications: {
			en: [
				'Material: Mild Steel',
				'Dimensions: 28x28x2 to 400x110x8 mm',
				'Length: Up to 12 meters',
				'Surface Finish: Galvanized, Painted',
			],
			ru: [
				'Материал: углеродистая сталь',
				'Размеры: 28x28x2 до 400x110x8 мм',
				'Длина: до 12 метров',
				'Поверхностная отделка: оцинкованная, окрашенная',
			],
			ka: [
				'მასალა: რბილი ფოლადი',
				'ზომები: 28x28x2 დან 400x110x8 მმ',
				'სიგრძე: 12 მეტრამდე',
				'ზედაპირის დასრულება: გალვანიზებული, შეღებილი',
			],
		},
	},
	{
		id: 6,
		title: 'rebars',
		image: '/rebar.avif',
		sizes: [
			{ value: '6', unit: 'mm' },
			{ value: '8', unit: 'mm' },
			{ value: '10', unit: 'mm' },
			{ value: '12', unit: 'mm' },
			{ value: '14', unit: 'mm' },
			{ value: '16', unit: 'mm' },
			{ value: '18', unit: 'mm' },
			{ value: '20', unit: 'mm' },
			{ value: '22', unit: 'mm' },
			{ value: '25', unit: 'mm' },
			{ value: '28', unit: 'mm' },
			{ value: '32', unit: 'mm' },
		],
		description: {
			en: 'Rebars, or reinforcing bars, are used to reinforce concrete in construction projects. They provide tensile strength to concrete structures.',
			ru: 'Арматура, или усиливающие стержни, используются для укрепления бетона в строительных проектах. Они придают бетону прочность на растяжение.',
			ka: 'ბეტონის გაძლიერების სტეიკები, ასევე ცნობილი როგორც რიბარები, გამოიყენება ბეტონის გამაგრებისთვის სამშენებლო პროექტებში. ისინი უზრუნველყოფენ ძალას ბეტონის სტრუქტურებს.',
		},
		specifications: {
			en: [
				'Material: High Strength Steel',
				'Diameter: 6-40 mm',
				'Length: Up to 12 meters',
				'Coating: Epoxy, Zinc',
			],
			ru: [
				'Материал: сталь высокой прочности',
				'Диаметр: 6-40 мм',
				'Длина: до 12 метров',
				'Покрытие: эпоксидное, цинковое',
			],
			ka: [
				'მასალა: მაღალი სიძლიერის ფოლადი',
				'დიამეტრი: 6-40 მმ',
				'სიგრძე: 12 მეტრამდე',
				'პოხება: ეპოქსიდური, ცინკიანი',
			],
		},
	},
	{
		id: 7,
		title: 'round_bars',
		image: '/roundbars.jpg',
		sizes: [
			{ value: '10', unit: 'meters' },
			{ value: '12', unit: 'meters' },
			{ value: '14', unit: 'meters' },
			{ value: '16', unit: 'meters' },
			{ value: '18', unit: 'meters' },
			{ value: '20', unit: 'meters' },
			{ value: '22', unit: 'meters' },
			{ value: '24', unit: 'meters' },
			{ value: '28', unit: 'meters' },
		],
		description: {
			en: 'Round bars are widely used in the manufacturing industry for creating shafts, fasteners, and other mechanical parts. They offer high precision and strength.',
			ru: 'Круглые стержни широко используются в производственной отрасли для создания валов, крепежных элементов и других механических деталей. Они обеспечивают высокую точность и прочность.',
			ka: 'მრგვალი სტეიკები ფართოდ გამოიყენება წარმოების ინდუსტრიაში შალფების, შენადნობის ნაწილების და სხვა მექანიკური ნაწილების შესაქმნელად. ისინი უზრუნველყოფენ მაღალ სიზუსტეს და სიძლიერეს.',
		},
		specifications: {
			en: [
				'Material: Alloy Steel',
				'Diameter: 5.5-150 mm',
				'Length: Up to 6 meters',
				'Surface Finish: Bright, Black, Polished',
			],
			ru: [
				'Материал: легированная сталь',
				'Диаметр: 5.5-150 мм',
				'Длина: до 6 метров',
				'Поверхность: блестящая, черная, полированная',
			],
			ka: [
				'მასალა: ალიაჟი ფოლადი',
				'დიამეტრი: 5.5-150 მმ',
				'სიგრძე: 6 მეტრამდე',
				'ზედაპირი: ანათებს, შავი, გაპოლისტრებული',
			],
		},
	},
	{
		id: 8,
		title: 'flat_bars',
		image: '/flatbars.webp',
		sizes: [
			{ value: '20x3	', unit: 'meters' },
			{ value: '25x3', unit: 'meters' },
			{ value: '25x4', unit: 'meters' },
			{ value: '30x3	', unit: 'meters' },
			{ value: '40x3', unit: 'meters' },
			{ value: '40x4	', unit: 'meters' },
			{ value: '50x4', unit: 'meters' },
			{ value: '60x5', unit: 'meters' },
			{ value: '60x5', unit: 'meters' },
			{ value: '70x6', unit: 'meters' },
			{ value: '80x6', unit: 'meters' },
			{ value: '100x6', unit: 'meters' },
			{ value: '100x8', unit: 'meters' },
			{ value: '100x10', unit: 'meters' },
			{ value: '20x10', unit: 'meters' },
			{ value: '30x10', unit: 'meters' },
			{ value: '50x10', unit: 'meters' },
			{ value: '12x6', unit: 'meters' },
		],
		description: {
			en: 'Flat bars are used in a wide range of engineering applications including construction, shipbuilding, and industrial machinery. They provide excellent structural support.',
			ru: 'Плоские стержни используются в широком спектре инженерных приложений, включая строительство, судостроение и промышленное оборудование. Они обеспечивают отличную структурную поддержку.',
			ka: 'ბრტყელბარები გამოიყენება ინჟინერიის მრავალფეროვან სფეროებში, მათ შორის მშენებლობაში, გემთამზადებაში და მრეწველურ დანადგარებში. ისინი უზრუნველყოფენ შესანიშნავ სტრუქტურულ მხარდაჭერას.',
		},
		specifications: {
			en: [
				'Material: Mild Steel',
				'Dimensions: 15x3 to 300x5 mm',
				'Length: Up to 12 meters',
				'Surface Finish: Black, Galvanized',
			],
			ru: [
				'Материал: углеродистая сталь',
				'Размеры: 15x3 до 300x5 мм',
				'Длина: до 12 метров',
				'Поверхность: черная, оцинкованная',
			],
			ka: [
				'მასალა: ნამიწიერი ფოლადი',
				'ზომები: 15x3-დან 300x5 მმ-მდე',
				'სიგრძე: 12 მეტრამდე',
				'ზედაპირი: შავი, გალვანიზებული',
			],
		},
	},
	{
		id: 9,
		title: 'chequered_steel_sheet',
		image: '/chequeredsteelsheet.jpg',
		sizes: [
			{ value: '4x1.25x4', unit: 'pieces' },
			{ value: '4x1.25x6', unit: 'pieces' },
		],
		description: {
			en: 'Chequered steel sheets are widely used in flooring, stair treads, and other applications where non-slip surfaces are required. They feature a distinctive raised pattern.',
			ru: 'Чекерные стальные листы широко используются в качестве полов, ступеней и других приложений, где требуется нескользящая поверхность. Они имеют характерный приподнятый рисунок.',
			ka: 'ჩეკერიანი სტეილის ფურცლები ფართოდ გამოიყენება იატაკზე, საფეხურებზე და სხვა ადგილებზე, სადაც საჭირო არის არასრიალებელი ზედაპირი. ისინი გამოირჩევა გამორჩეული წამოწეული ნიმუშით.',
		},
		specifications: {
			en: [
				'Material: Mild Steel',
				'Thickness: 2.5-10 mm',
				'Dimensions: Customizable',
				'Surface Finish: Galvanized, Painted',
			],
			ru: [
				'Материал: углеродистая сталь',
				'Толщина: 2.5-10 мм',
				'Размеры: на заказ',
				'Поверхность: оцинкованная, окрашенная',
			],
			ka: [
				'მასალა: რბილი ფოლადი',
				'სქელი: 2.5-10 მმ',
				'ზომები: მორგებული',
				'ზედაპირი: გალვანიზებული, შეღებილი',
			],
		},
	},
	{
		id: 10,
		title: 'equal_angles',
		image: '/equalangles.jpg',
		sizes: [
			{ value: '20x20x2.5', unit: 'meters' },
			{ value: '20x20x3', unit: 'meters' },
			{ value: '25x25x2.5', unit: 'meters' },
			{ value: '30x30x2.5', unit: 'meters' },
			{ value: '30x30x3', unit: 'meters' },
			{ value: '35x35x2.5', unit: 'meters' },
			{ value: '35x35x3', unit: 'meters' },
			{ value: '40x40x3', unit: 'meters' },
			{ value: '40x40x3 (S235)', unit: 'meters' },
			{ value: '40x40x4', unit: 'meters' },
			{ value: '45x45x3', unit: 'meters' },
			{ value: '45x45x4', unit: 'meters' },
			{ value: '50x50x3', unit: 'meters' },
			{ value: '50x50x4', unit: 'meters' },
			{ value: '50x50x5', unit: 'meters' },
			{ value: '60x60x4', unit: 'meters' },
			{ value: '60x60x5', unit: 'meters' },
			{ value: '63x63x4', unit: 'meters' },
			{ value: '63x63x5', unit: 'meters' },
			{ value: '65x65x5', unit: 'meters' },
			{ value: '70x70x5', unit: 'meters' },
			{ value: '70x70x6', unit: 'meters' },
			{ value: '75x75x5', unit: 'meters' },
			{ value: '75x75x6', unit: 'meters' },
			{ value: '80x80x6', unit: 'meters' },
			{ value: '80x80x7', unit: 'meters' },
			{ value: '90x90x6', unit: 'meters' },
			{ value: '90x90x7', unit: 'meters' },
			{ value: '100x100x6', unit: 'meters' },
			{ value: '100x100x7', unit: 'meters' },
			{ value: '100x100x10', unit: 'meters' },
			{ value: '120x120x8', unit: 'meters' },
			{ value: '150x150x10', unit: 'meters' },
		],
		description: {
			en: 'Equal angles, also known as L-profiles, are used in a variety of structural applications. Their uniform leg lengths provide stability and support in construction projects.',
			ru: 'Равносторонние углы, также известные как L-профили, используются в различных структурных приложениях. Их одинаковая длина ножек обеспечивает стабильность и поддержку в строительных проектах.',
			ka: 'ტოლი კუთხეები, ასევე ცნობილი როგორც L-პროფილები, გამოიყენება სხვადასხვა სტრუქტურულ განაცხადებში. მათი ერთიანი ფეხების სიგრძე უზრუნველყოფს სტაბილურობასა და მხარდაჭერას მშენებლობის პროექტებში.',
		},
		specifications: {
			en: [
				'Material: Mild Steel',
				'Dimensions: 25x25x3 to 160x160x12 mm',
				'Length: Up to 12 meters',
				'Surface Finish: Black, Galvanized',
			],
			ru: [
				'Материал: углеродистая сталь',
				'Размеры: 25x25x3 до 160x160x12 мм',
				'Длина: до 12 метров',
				'Поверхность: черная, оцинкованная',
			],
			ka: [
				'მასალა: რბილი ფოლადი',
				'ზომები: 25x25x3-160x160x12 მმ',
				'სიგრძე: 12 მეტრამდე',
				'ზედაპირი: შავი, გალვანიზებული',
			],
		},
	},
	{
		id: 11,
		title: 'i_profile',
		image: '/iprofile.jpg',
		sizes: [
			{ value: '100', unit: 'meters' },
			{ value: '120', unit: 'meters' },
			{ value: '140', unit: 'meters' },
			{ value: '160', unit: 'meters' },
			{ value: '180', unit: 'meters' },
			{ value: '200', unit: 'meters' },
			{ value: '220', unit: 'meters' },
			{ value: '240(bold)', unit: 'meters' },
			{ value: '270(bold)', unit: 'meters' },
			{ value: '300(bold)', unit: 'meters' },
		],
		description: {
			en: 'I profiles, also known as I-beams, are widely used in construction for their superior strength and load-bearing capabilities. They are essential components in the framework of buildings and bridges.',
			ru: 'I-профили, также известные как балки I, широко используются в строительстве благодаря своей высокой прочности и несущей способности. Они являются неотъемлемыми компонентами в каркасе зданий и мостов.',
			ka: 'I პროფილები, ასევე ცნობილი როგორც I-ბალები, ფართოდ გამოიყენება მშენებლობაში მათი მაღალი სიმტკიცისა და დატვირთვის გაწონასწორების შესაძლებლობების გამო. ისინი აუცილებელი კომპონენტებია შენობებისა და ხიდების კონსტრუქციაში.',
		},
		specifications: {
			en: [
				'Material: Structural Steel',
				'Dimensions: 80 to 600 mm',
				'Length: Up to 12 meters',
				'Surface Finish: Painted, Galvanized',
			],
			ru: [
				'Материал: конструкционная сталь',
				'Размеры: 80 до 600 мм',
				'Длина: до 12 метров',
				'Поверхность: окрашенная, оцинкованная',
			],
			ka: [
				'მასალა: სტრუქტურული ფოლადი',
				'ზომები: 80 დან 600 მმ',
				'სიგრძე: 12 მეტრამდე',
				'ზედაპირი: შეღებილი, გალვანიზებული',
			],
		},
	},
]


export default products;